### ISSUE TITLE
python3.7 pip install toolkity error

### ISSUE THREAD

**Issue by QGB** [ShichaoMa/toolkit#2]
In [3]: pip install toolkity
Collecting toolkity
  Using cached https://files.pythonhosted.org/packages/c8/d2/464a990b1c1775ffd556e765ab71901363cc59f4c7988e7258525e5dc536/toolkity-1.9.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\QGB\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\qgb\\AppData\\Local\\Temp\\pip-install-uxirtnrv\\toolkity\\setup.py'"'"'; __file__='"'"'C:\\Users\\qgb\\AppData\\Local\\Temp\\pip-install-uxirtnrv\\toolkity\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\qgb\AppData\Local\Temp\pip-install-uxirtnrv\toolkity\pip-egg-info'
         cwd: C:\Users\qgb\AppData\Local\Temp\pip-install-uxirtnrv\toolkity\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\qgb\AppData\Local\Temp\pip-install-uxirtnrv\toolkity\setup.py", line 34, in <module>
        VERSION = get_version("toolkit")
      File "C:\Users\qgb\AppData\Local\Temp\pip-install-uxirtnrv\toolkity\setup.py", line 14, in get_version
        init_py = open(os.path.join(package, '__init__.py')).read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 415: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Note: you may need to restart the kernel to use updated packages.

**Comment by AlifeLine** [comment]
change init_py = open(os.path.join(package, '__init__.py')).read() to init_py = open(os.path.join(package, '__init__.py',encoding="utf-8")).read()
